// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ComicProcessor is an autogenerated mock type for the ComicProcessor type
type ComicProcessor struct {
	mock.Mock
}

// FullProcess provides a mock function with given fields: text
func (_m *ComicProcessor) FullProcess(text string) ([]string, error) {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for FullProcess")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(text)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewComicProcessor creates a new instance of ComicProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComicProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComicProcessor {
	mock := &ComicProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
