version: '3.1'

services:
  auth_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: xkcd_user
      POSTGRES_PASSWORD: xkcd_password
      POSTGRES_DB: xkcd
    ports:
      - "5431:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
  xkcd_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: xkcd_user
      POSTGRES_PASSWORD: xkcd_password
      POSTGRES_DB: xkcd
    ports:
      - "5433:5432"
    volumes:
      - xkcd_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  xkcd_server:
    build:
      context: .
      dockerfile: ./xkcdserver.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - xkcd_postgres
      - redis
      - auth_server
  web_server:
    build:
      context: .
      dockerfile: ./webserver.Dockerfile
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - xkcd_server
  auth_server:
    build:
      context: .
      dockerfile: ./authserver.Dockerfile
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      - auth_postgres
volumes:
  xkcd_postgres_data:
  auth_postgres_data:
